# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 636d067b10a13976e45093af49fc3440d09fe4dbfc3fa748e2fede6c8e6ff16fd0b488f6c2f7151cb2b7a65c50f1f2859dce330d73fbce445d4a001cde49f67a

test:
  secret_key_base: 0a27fc77215b6e90e604bc9ef196297e3b3e578df6a01f04ee828b595332731b6cb3d8563d373948f29fcb54232cac601da6fff21062c021d6f014c6b2cd746d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
